import '../../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 text-gray-900">
        {children}
      </div>
    </main>
  );
}
